global:
  component: "summarizer"

deployment:
  replicas: 1
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  imagePullSecrets:
    - "regcred"
  containers:
    summarizer:
      isEnabled: true
      repository: "886748703774.dkr.ecr.eu-central-1.amazonaws.com"
      image: "ariellahiany/kaltura"
      tag: "v0.2.0"
      imagePullPolicy: "IfNotPresent"
      readinessProbe:
        type: "httpGet"
        path: "/health"
        port: 8000
        initialDelaySeconds: 10
        periodSeconds: 5
        successThreshold: 3
        failureThreshold: 3
      livenessProbe:
        type: "httpGet"
        path: "/health"
        port: 8000
        initialDelaySeconds: 10
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      ports:
        http:
          protocol: "TCP"
          containerPort: 8000
      args:
        - "gunicorn"
        - "main:application"
        - "--workers"
        - "1"
        - "--bind"
        - "0.0.0.0:8000"

service:
  type: "ClusterIP"
  ports:
    http:
      protocol: "TCP"
      port: 8000
      targetPort: 8000
